package selftest

import (
	"encoding/json"
	"strings"
)

// runSection26 regression-tests T-05/T-08: dependency-order board
// tiering, computed instead of traced by hand -- the exact by-hand
// rule verified twice this session against a real reference
// (docs/proposals/t08-board-target-shape.md and its "Path to Boards"
// companion), now generated by `board --definition ... --axis
// dependency_order` via register.BuildGraph/DetectCycle/TierOf and
// board.renderDependencyOrder.
//
// T-30 (fixed): `board --definition ... --format json` used to fail
// validation on EVERY axis ("data.legend: field cannot be null") --
// DefinitionReport.Legend has no `omitempty` and a nil Go slice
// marshals to JSON null, which queryfy's strict-mode schema rejects
// even for a field without .Required(). Fixed in pkg/board/definition.go
// by normalizing a nil Legend to an empty slice at both construction
// sites, the same discipline Columns/Overflow.Items already followed.
// The json-format check below exercises this directly against the
// same linear-chain fixture used for the text-format check.
func runSection26(g *gate, root string) int {
	self := g.self

	// -- linear chain: T-70 (tier 0) -> T-71 (tier 1) -> T-72 (tier 2) --
	chainDir := root + "/section26-chain"
	mustWrite(chainDir+"/.repoman.json", `{"id_prefix":"T","id_separator":"-"}`)
	mustWrite(chainDir+"/docs/TRACKING.md",
		"# Tracking\n\n"+
			"| ID | Summary | Theme | Priority | Status | Blocks/after |\n"+
			"|----|---------|-------|----------|--------|--------|\n\n"+
			"### T-70. root, no blockers\n\n"+
			"Theme: chain · Priority: P2 · Status: ☐\n\n"+
			"Body.\n\n"+
			"### T-71. depends on T-70\n\n"+
			"Theme: chain · Priority: P2 · Status: ☐ · Blocks/after: T-70\n\n"+
			"Body.\n\n"+
			"### T-72. depends on T-71\n\n"+
			"Theme: chain · Priority: P2 · Status: ☐ · Blocks/after: T-71\n\n"+
			"Body.\n\n")
	mustWrite(chainDir+"/docs/RESOLVED.md", "# Resolved\n\nClosed items, newest first.\n")

	defPath := root + "/dep-order.json"
	mustWrite(defPath, `{`+
		`"schema":"gorepoman.workspace.board/1",`+
		`"name":"dep-check",`+
		`"axis":"dependency_order",`+
		`"scope":{"projects":[]},`+
		`"overflow":{"hidden":false}}`)

	r := run(self, chainDir, "board", ".", "--definition", defPath, "--format", "text")
	if !g.check(r.code == 0, "dependency_order: a linear chain renders without error", r.stdout+r.stderr) {
		return 1
	}
	tier0 := strings.Index(r.stdout, "Tier 0")
	tier1 := strings.Index(r.stdout, "Tier 1")
	tier2 := strings.Index(r.stdout, "Tier 2")
	t70 := strings.Index(r.stdout, "T-70")
	t71 := strings.Index(r.stdout, "T-71")
	t72 := strings.Index(r.stdout, "T-72")
	if !g.check(tier0 >= 0 && tier1 >= 0 && tier2 >= 0 &&
		t70 > tier0 && t70 < tier1 && t71 > tier1 && t71 < tier2 && t72 > tier2,
		"dependency_order: T-70/T-71/T-72 land in tier 0/1/2 respectively, "+
			"each one after its own blocker", r.stdout) {
		return 1
	}

	// -- a closed blocker (not in the open-items graph at all) does not
	// hold its dependent back: T-73's Blocks/after names T-70, which is
	// deliberately absent from THIS fixture's open items (standing in
	// for "closed"), and should land T-73 in tier 0, not be stuck
	// waiting on a blocker this graph never sees -- the same rule that
	// keeps a real project's closed items from silently pinning open
	// ones in place forever.
	closedDir := root + "/section26-closed-blocker"
	mustWrite(closedDir+"/.repoman.json", `{"id_prefix":"T","id_separator":"-"}`)
	mustWrite(closedDir+"/docs/TRACKING.md",
		"# Tracking\n\n"+
			"| ID | Summary | Theme | Priority | Status | Blocks/after |\n"+
			"|----|---------|-------|----------|--------|--------|\n\n"+
			"### T-73. blocks-after a closed item\n\n"+
			"Theme: chain · Priority: P2 · Status: ☐ · Blocks/after: T-70\n\n"+
			"Body.\n\n")
	mustWrite(closedDir+"/docs/RESOLVED.md", "# Resolved\n\nClosed items, newest first.\n")

	r = run(self, closedDir, "board", ".", "--definition", defPath, "--format", "text")
	if !g.check(r.code == 0 && strings.Contains(r.stdout, "Tier 0") && strings.Contains(r.stdout, "T-73") &&
		!strings.Contains(r.stdout, "Tier 1"),
		"dependency_order: blocks-after a closed (not-open) item does not hold the "+
			"dependent back -- it lands in tier 0, not stuck waiting on a blocker "+
			"this graph never sees", r.stdout) {
		return 1
	}

	// -- a real cycle: reported as an actionable error naming a concrete
	// path, not a crash, an infinite loop, or a silently wrong tier.
	cycleDir := root + "/section26-cycle"
	mustWrite(cycleDir+"/.repoman.json", `{"id_prefix":"T","id_separator":"-"}`)
	mustWrite(cycleDir+"/docs/TRACKING.md",
		"# Tracking\n\n"+
			"| ID | Summary | Theme | Priority | Status | Blocks/after |\n"+
			"|----|---------|-------|----------|--------|--------|\n\n"+
			"### T-80. cycle A\n\n"+
			"Theme: chain · Priority: P2 · Status: ☐ · Blocks/after: T-81\n\n"+
			"Body.\n\n"+
			"### T-81. cycle B\n\n"+
			"Theme: chain · Priority: P2 · Status: ☐ · Blocks/after: T-80\n\n"+
			"Body.\n\n")
	mustWrite(cycleDir+"/docs/RESOLVED.md", "# Resolved\n\nClosed items, newest first.\n")

	r = run(self, cycleDir, "board", ".", "--definition", defPath, "--format", "text")
	if !g.check(r.code != 0 && strings.Contains(r.stderr, "cycle") &&
		strings.Contains(r.stderr, "T-80") && strings.Contains(r.stderr, "T-81"),
		"dependency_order: a real cycle is reported as an actionable error naming "+
			"a concrete path, not a crash or a silently wrong tier", r.stdout+r.stderr) {
		return 1
	}

	// -- a self-loop (A blocks-after A) is caught the same way, not as a
	// special case that slips past the general cycle check.
	selfLoopDir := root + "/section26-selfloop"
	mustWrite(selfLoopDir+"/.repoman.json", `{"id_prefix":"T","id_separator":"-"}`)
	mustWrite(selfLoopDir+"/docs/TRACKING.md",
		"# Tracking\n\n"+
			"| ID | Summary | Theme | Priority | Status | Blocks/after |\n"+
			"|----|---------|-------|----------|--------|--------|\n\n"+
			"### T-85. blocks after itself\n\n"+
			"Theme: chain · Priority: P2 · Status: ☐ · Blocks/after: T-85\n\n"+
			"Body.\n\n")
	mustWrite(selfLoopDir+"/docs/RESOLVED.md", "# Resolved\n\nClosed items, newest first.\n")

	r = run(self, selfLoopDir, "board", ".", "--definition", defPath, "--format", "text")
	if !g.check(r.code != 0 && strings.Contains(r.stderr, "cycle") && strings.Contains(r.stderr, "T-85"),
		"dependency_order: a self-loop (A blocks-after A) is caught the same way a "+
			"longer cycle is, not as an unhandled special case", r.stdout+r.stderr) {
		return 1
	}

	// -- explicit columns narrower than the tiers present: deeper items
	// go to Overflow, exactly as workspace/schema.go documents for this
	// axis ("position IS the value... deeper than the configured
	// columns goes to Overflow"), not silently dropped or auto-extended.
	narrowDefPath := root + "/dep-order-narrow.json"
	mustWrite(narrowDefPath, `{`+
		`"schema":"gorepoman.workspace.board/1",`+
		`"name":"dep-check-narrow",`+
		`"axis":"dependency_order",`+
		`"scope":{"projects":[]},`+
		`"columns":[{"label":"Now"},{"label":"Next"}],`+
		`"overflow":{"hidden":false}}`)

	r = run(self, chainDir, "board", ".", "--definition", narrowDefPath, "--format", "text")
	if !g.check(r.code == 0 && strings.Contains(r.stdout, "Now") && strings.Contains(r.stdout, "Next") &&
		strings.Contains(r.stdout, "Overflow") && strings.Contains(r.stdout, "T-72"),
		"dependency_order: an item whose tier is deeper than the configured columns "+
			"goes to Overflow rather than being silently dropped or given its own "+
			"unconfigured column", r.stdout) {
		return 1
	}

	// -- html format succeeds too (the actual consumer format for a
	// persisted board), not skipping a non-text format just because
	// another one (json, until T-30 fixed it) once had a filed bug.
	r = run(self, chainDir, "board", ".", "--definition", defPath, "--format", "html")
	if !g.check(r.code == 0 && strings.Contains(r.stdout, "<!DOCTYPE") && strings.Contains(r.stdout, "T-70"),
		"dependency_order: --format html succeeds and contains the rendered items",
		r.stdout[:min(len(r.stdout), 400)]+r.stderr) {
		return 1
	}

	// -- json format succeeds too: T-30 regression check. This used to
	// fail validation on every axis ("data.legend: field cannot be
	// null") because DefinitionReport.Legend has no `omitempty` and a
	// nil Go slice marshals to JSON null; fixed in pkg/board/definition.go
	// by normalizing nil to an empty slice. Assert the envelope actually
	// parses and carries the same tiered structure the text/html checks
	// above already confirmed, not just that the process exits 0.
	r = run(self, chainDir, "board", ".", "--definition", defPath, "--format", "json")
	if !g.check(r.code == 0, "dependency_order: --format json succeeds (T-30 regression)", r.stdout+r.stderr) {
		return 1
	}
	var jsonEnvelope struct {
		Data struct {
			Columns []struct {
				Label string `json:"label"`
				Items []struct {
					ID string `json:"id"`
				} `json:"items"`
			} `json:"columns"`
			Legend []interface{} `json:"legend"`
		} `json:"data"`
	}
	if err := json.Unmarshal([]byte(r.stdout), &jsonEnvelope); err != nil {
		if !g.check(false, "dependency_order: --format json output actually parses as JSON", r.stdout) {
			return 1
		}
	}
	gotTier := map[string]string{}
	for _, col := range jsonEnvelope.Data.Columns {
		for _, item := range col.Items {
			gotTier[item.ID] = col.Label
		}
	}
	if !g.check(jsonEnvelope.Data.Legend != nil &&
		gotTier["T-70"] == "Tier 0" && gotTier["T-71"] == "Tier 1" && gotTier["T-72"] == "Tier 2",
		"dependency_order: the json path sees the same tiered structure as the text/html "+
			"paths, and legend decodes as an empty array rather than null",
		r.stdout) {
		return 1
	}

	return runSection27(g, root)
}
