// Package strreplace implements format-aware, journaled, base64-payload
// text substitution -- translated from repoman/str_replace_extended.py.
//
// Built to retire the failure class that direct str_replace/sed/awk
// substitution invites: content passing through a shell/argv quoting
// layer before it reaches disk, and edits landing without ever
// checking whether they broke the file's own syntax. Two recorded
// incidents in this project's own session history motivated it
// directly: a replacement's escape sequences (\n, \t) silently taken
// literally by bash's $'...' quoting because an apostrophe inside the
// content closed the quote early, and a duplicated line produced by a
// replacement whose own leading text overlapped its anchor span,
// applied faithfully by a tool with no way to notice.
//
// NEVER accepts search/replace text as CLI arguments. The payload is
// JSON, read from stdin or a file, with all search/replace content
// carried as base64 of raw UTF-8 bytes -- so a backtick, an
// apostrophe, a newline, or any other character with shell meaning
// can never be reinterpreted before it reaches this tool.
//
// CLI:
//
//	repoman strreplace apply [-|payload.json]
//	repoman strreplace selftest
//
// Library:
//
//	result := strreplace.ApplyPayloadJSON(raw)   // []byte in, map out
//
// Payload schema (v1), one JSON document:
//
//	{
//	  "v": 1,
//	  "atomic": true,                    // default true; see below
//	  "defaults": {"syntax_check": true, "dry_run": false},
//	  "ops": [
//	    {
//	      "op": "sub",                   // default "sub" if omitted
//	      "file": "path/to/file",
//	      "search_b64": "<base64 of raw utf-8 search text>",
//	      "replace_b64": "<base64 of raw utf-8 replacement text>",
//	      "expect": 1,                   // REQUIRED, no default -- exact
//	                                      // match count, or the op refuses
//	      "roles": ["go-code"],          // REQUIRED -- every match's
//	                                      // classified role must be one of
//	                                      // these, or the op refuses with
//	                                      // the real census printed
//	      "occurrences": null,           // null = all matches (requires a
//	                                      // uniform role); [2, 4] = only
//	                                      // those 1-indexed matches
//	      "dry_run": false,              // overrides defaults.dry_run
//	      "syntax_check": true           // overrides defaults.syntax_check
//	    },
//	    {"op": "gen_markers", "file": "path/to/file", "count": 2},
//	    {"op": "sweep_markers", "file": "path/to/file"}
//	  ]
//	}
//
// atomic (default true): when multiple ops are staged, either every
// op in the payload applies or none do. Ops targeting the same file
// apply in listed order against each other's in-memory result
// (mirroring pkg/ed's own per-file staged-write discipline);
// syntax-check runs once per touched file against its final staged
// content. atomic:false applies ops independently, collecting
// successes and failures separately -- use only when a later op's
// failure genuinely should not undo an earlier one.
//
// Refusal classes (op-level; exit 1 overall if any refuse under
// atomic mode, nothing written; each reason appears on stderr AND in
// the JSON result's own "error" field):
//
//	invalid-utf8-file        file does not decode as UTF-8
//	invalid-utf8-payload     search_b64/replace_b64 does not decode
//	normalization-mismatch   0 raw matches, but N would match under a
//	                          different Unicode normalization form
//	count-mismatch           occurrences found != expect
//	role-mismatch            census is not a subset of the asserted
//	                          roles; real census printed
//	delimiter-break          the edit changes the syntactic role of text
//	                          immediately following it (a differential
//	                          re-classification, not a full parser) --
//	                          catches unescaped delimiters landing inside
//	                          string/comment context
//	syntax-check-failed      post-apply format validator failed; the
//	                          write is rolled back before this returns
//
// Every genuinely-applied op (not dry-run, not marker ops) is
// recorded in pkg/ed's own journal (.ed-journal.json) via ed.Record --
// one undo history for both tools regardless of which one made a
// given edit. `repoman ed mark` / `repoman ed undo` / `repoman ed log`
// all see these edits too.
//
// Markers (gen_markers / sweep_markers): for workflows that stage a
// change in two steps (insert a marker, later replace between
// markers), markers are generated by this tool, never supplied by the
// caller as literal text -- collision-checked against the live file
// content before being returned, using the U+27E6/U+27E7 MATHEMATICAL
// WHITE SQUARE BRACKET pair, valid UTF-8, printable, and not syntax in
// any format this tool validates. sweep_markers removes every marker
// this tool's own format ever produced, recognisable by a fixed
// prefix, so a marker generated in a crashed or abandoned session
// cannot silently survive.
//
// ADAPTATION FROM THE PYTHON ORIGINAL, documented once here rather
// than scattered: _check_normalization used Python's stdlib
// unicodedata module (full Unicode NFC/NFD normalization). Go's
// standard library has no equivalent, and golang.org/x/text (which
// does) is a third-party module this project's zero-dependency
// convention deliberately avoids and this sandbox's network policy
// cannot fetch cleanly regardless. checkNormalization below instead
// implements a bounded precomposed<->decomposed table for the Latin-1
// Supplement accented letters -- exactly the "accented Spanish text"
// case the original docstring names as the live concern. Text using
// other scripts' composed/decomposed forms will not be caught by this
// check; normalization-mismatch simply won't fire for those, the same
// "documented gap, not silently wrong" pattern pkg/roles already uses
// for its own YAML block-scalar and shell-heredoc limitations.
package strreplace

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base32"
	"encoding/base64"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/ha1tch/gorepoman/pkg/roles"
)

const (
	MarkerOpen  = "\u27e6"
	MarkerClose = "\u27e7"
)

var markerRe = regexp.MustCompile(regexp.QuoteMeta(MarkerOpen) + `RM:[a-z0-9]{16}` + regexp.QuoteMeta(MarkerClose))

// Refused carries a (class, message) pair -- every refusal in this
// package is one of these, surfaced to the caller via the returned
// result map's "error" field, never a bare error string.
type Refused struct {
	Cls     string
	Message string
}

func (r *Refused) Error() string { return fmt.Sprintf("%s: %s", r.Cls, r.Message) }

func refused(cls, format string, args ...interface{}) *Refused {
	return &Refused{Cls: cls, Message: fmt.Sprintf(format, args...)}
}

// ── payload decoding ────────────────────────────────────────────────

type opJSON struct {
	Op          *string  `json:"op"`
	File        string   `json:"file"`
	SearchB64   *string  `json:"search_b64"`
	ReplaceB64  *string  `json:"replace_b64"`
	Expect      *int     `json:"expect"`
	Roles       []string `json:"roles"`
	Occurrences []int    `json:"occurrences"`
	DryRun      *bool    `json:"dry_run"`
	SyntaxCheck *bool    `json:"syntax_check"`
	Count       *int     `json:"count"`
}

func (o opJSON) kind() string {
	if o.Op != nil {
		return *o.Op
	}
	return "sub"
}

type defaultsJSON struct {
	SyntaxCheck *bool `json:"syntax_check"`
	DryRun      *bool `json:"dry_run"`
}

type payloadJSON struct {
	V         *int         `json:"v"`
	Atomic    *bool        `json:"atomic"`
	Defaults  defaultsJSON `json:"defaults"`
	Ops       []opJSON     `json:"ops"`
	DryRunAll *bool        `json:"dry_run_all"`
}

func b64DecodeUTF8(s, what string) (string, error) {
	raw, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		return "", refused("invalid-utf8-payload", "%s: not valid base64 (%v)", what, err)
	}
	if !utf8.Valid(raw) {
		return "", refused("invalid-utf8-payload", "%s: base64 decodes but is not valid UTF-8", what)
	}
	return string(raw), nil
}

func isValidUTF8(b []byte) bool { return utf8.Valid(b) }

// readFileUTF8 reads a file and requires it decode as UTF-8, matching
// _read_file_utf8's own refusal class.
func readFileUTF8(path string) (string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", refused("invalid-utf8-file", "%s: cannot read (%v)", path, err)
	}
	if !utf8.Valid(raw) {
		return "", refused("invalid-utf8-file", "%s: not valid UTF-8", path)
	}
	return string(raw), nil
}

// ── matching ─────────────────────────────────────────────────────────

// findAll returns every (possibly overlapping) byte offset at which
// search occurs in text, stepping by 1 after each hit -- the same
// overlap-permitting semantics pkg/ed's own `sub` command and Python's
// str.find(search, i+1) both use.
func findAll(text, search string) []int {
	if search == "" {
		return nil
	}
	var out []int
	i := strings.Index(text, search)
	for i != -1 {
		out = append(out, i)
		next := strings.Index(text[i+1:], search)
		if next == -1 {
			break
		}
		i = i + 1 + next
	}
	return out
}

// ── normalization (see the package doc comment's ADAPTATION note) ──

type diacritic struct {
	precomposed rune
	base        rune
	mark        rune
}

var diacriticsTable = buildDiacriticsTable()

func buildDiacriticsTable() []diacritic {
	type entry struct {
		base rune
		mark rune
	}
	// Latin-1 Supplement's accented letters, grouped by combining
	// mark -- covers the accented-Spanish-text case the original
	// docstring names directly (á é í ó ú ñ ü), plus the rest of
	// Latin-1's own accented range for broader Western-European
	// coverage at negligible extra cost.
	groups := map[rune][]rune{
		0x0300: {'a', 'e', 'i', 'o', 'u'},      // grave
		0x0301: {'a', 'e', 'i', 'o', 'u', 'y'}, // acute
		0x0302: {'a', 'e', 'i', 'o', 'u'},      // circumflex
		0x0303: {'a', 'n', 'o'},                // tilde
		0x0308: {'a', 'e', 'i', 'o', 'u', 'y'}, // diaeresis
		0x030a: {'a'},                          // ring above
		0x0327: {'c'},                          // cedilla
	}
	precomposedFor := map[[2]rune]rune{
		{'a', 0x0300}: 'à', {'a', 0x0301}: 'á', {'a', 0x0302}: 'â', {'a', 0x0303}: 'ã', {'a', 0x0308}: 'ä', {'a', 0x030a}: 'å',
		{'e', 0x0300}: 'è', {'e', 0x0301}: 'é', {'e', 0x0302}: 'ê', {'e', 0x0308}: 'ë',
		{'i', 0x0300}: 'ì', {'i', 0x0301}: 'í', {'i', 0x0302}: 'î', {'i', 0x0308}: 'ï',
		{'n', 0x0303}: 'ñ',
		{'o', 0x0300}: 'ò', {'o', 0x0301}: 'ó', {'o', 0x0302}: 'ô', {'o', 0x0303}: 'õ', {'o', 0x0308}: 'ö',
		{'u', 0x0300}: 'ù', {'u', 0x0301}: 'ú', {'u', 0x0302}: 'û', {'u', 0x0308}: 'ü',
		{'y', 0x0301}: 'ý', {'y', 0x0308}: 'ÿ',
		{'c', 0x0327}: 'ç',
	}
	var out []diacritic
	for mark, bases := range groups {
		for _, base := range bases {
			pre, ok := precomposedFor[[2]rune{base, mark}]
			if !ok {
				continue
			}
			out = append(out, diacritic{precomposed: pre, base: base, mark: rune(mark)})
			// Uppercase variant: base uppercased, precomposed uppercased.
			upperBase := []rune(strings.ToUpper(string(base)))[0]
			upperPre := []rune(strings.ToUpper(string(pre)))[0]
			out = append(out, diacritic{precomposed: upperPre, base: upperBase, mark: rune(mark)})
		}
	}
	return out
}

func nfcApprox(s string) string {
	runes := []rune(s)
	var out []rune
	i := 0
	for i < len(runes) {
		if i+1 < len(runes) {
			matched := false
			for _, d := range diacriticsTable {
				if runes[i] == d.base && runes[i+1] == d.mark {
					out = append(out, d.precomposed)
					i += 2
					matched = true
					break
				}
			}
			if matched {
				continue
			}
		}
		out = append(out, runes[i])
		i++
	}
	return string(out)
}

func nfdApprox(s string) string {
	runes := []rune(s)
	var out []rune
	for _, r := range runes {
		decomposed := false
		for _, d := range diacriticsTable {
			if r == d.precomposed {
				out = append(out, d.base, d.mark)
				decomposed = true
				break
			}
		}
		if !decomposed {
			out = append(out, r)
		}
	}
	return string(out)
}

// checkNormalization is only called when the raw search found zero
// matches. Reports, without guessing which is "correct", whether
// search would match under an NFC- or NFD-like transform -- see the
// package doc comment's ADAPTATION note for the scope of what this
// bounded table catches.
func checkNormalization(text, search string) error {
	hits := map[string]int{}
	if n := len(findAll(nfcApprox(text), nfcApprox(search))); n > 0 {
		hits["NFC"] = n
	}
	if n := len(findAll(nfdApprox(text), nfdApprox(search))); n > 0 {
		hits["NFD"] = n
	}
	if len(hits) == 0 {
		return nil
	}
	forms := make([]string, 0, len(hits))
	for f := range hits {
		forms = append(forms, f)
	}
	sort.Strings(forms)
	var parts []string
	for _, f := range forms {
		parts = append(parts, fmt.Sprintf("%d under %s", hits[f], f))
	}
	return refused("normalization-mismatch",
		"0 raw matches, but %s -- the file and the search payload disagree on Unicode "+
			"normalization form. Re-encode the search text from the file's own actual bytes "+
			"rather than resubmitting; do not auto-normalize.", strings.Join(parts, ", "))
}

// ── delimiter-integrity precheck ────────────────────────────────────

// contentRoles are roles where being INSIDE at the start of an edit
// means the entire replacement must stay inside throughout its own
// span -- escaping and re-entering with a BALANCED pair of delimiters
// (e.g. Go's own `hello" + injected + "` pattern) restores quote
// PARITY by the time the tail is reached, so a check that only
// samples text AFTER the replacement never sees it: both "before" and
// "after" are correctly inside the string, and the injected code in
// between is invisible to a check that never looks inside the
// replacement's own span.
var contentRoles = map[string]bool{
	"go-backtick-string": true, "go-dquote-string": true, "go-comment": true,
	"python-string": true, "python-comment": true,
	"json-string": true,
	"yaml-string": true, "yaml-comment": true,
	"shell-squote-string": true, "shell-dquote-string": true, "shell-backtick-string": true, "shell-comment": true,
	"md-fence": true, "md-inline-code": true,
}

var precheckOffsets = []int{0, 1, 2, 5, 10, 20, 40, 80, 160, 320, 640, 1280, 2560, 5120}

const precheckCap = 20000

// checkDelimiterIntegrity is a two-part differential re-classification,
// not a full parser.
//
// Part A (interior): only when the edit STARTS inside a content role
// (a string/comment of some kind) -- every offset within the
// replacement's own span must classify as that SAME role throughout.
// Any deviation means the replacement contains an unescaped delimiter
// that exits the enclosing construct, whether or not a later
// delimiter in the same replacement re-enters it (a balanced
// escape-and-reenter is exactly what this part exists to catch, and
// exactly what an after-only check cannot see).
//
// Part B (tail): for every edit regardless of starting role, the role
// at increasing distances after the replacement must match the role
// at the same distances after the original match -- catches an
// UNbalanced delimiter (opened, never closed within the replacement)
// that changes what everything downstream is classified as.
//
// Not caught by either part, by design, and left to the post-apply
// syntax validator instead: brace/paren/bracket balance, since no
// role here tracks nesting depth, only string/comment state.
func checkDelimiterIntegrity(path, original string, start, end int, replacement string) error {
	newText := original[:start] + replacement + original[end:]
	newPoint := start + len(replacement)
	startRole := roles.Classify(path, original, start)

	if contentRoles[startRole] {
		interiorLen := len(replacement)
		stride := 1
		if interiorLen > 2000 {
			stride = interiorLen / 2000
			if stride < 1 {
				stride = 1
			}
		}
		for off := 0; off < interiorLen; off += stride {
			role := roles.Classify(path, newText, start+off)
			if role != startRole {
				return refused("delimiter-break",
					"role at +%d char(s) INTO the replacement changed from %q (the role the edit "+
						"starts inside) to %q -- the replacement contains an unescaped delimiter for "+
						"this file's own format that exits the enclosing %s, whether or not it later "+
						"re-enters one. Escape the delimiter, or if exiting is genuinely intended, "+
						"split into separate ops so each one's own starting role matches its own content.",
					off, startRole, role, startRole)
			}
		}
	}

	origLen, newLen := len(original), len(newText)
	for _, off := range precheckOffsets {
		if off > precheckCap {
			break
		}
		oo, no := end+off, newPoint+off
		if oo >= origLen || no >= newLen {
			break
		}
		roleOrig := roles.Classify(path, original, oo)
		roleNew := roles.Classify(path, newText, no)
		if roleOrig != roleNew {
			return refused("delimiter-break",
				"role at +%d char(s) after the edit changed from %q to %q -- the replacement likely "+
					"contains an unescaped delimiter for this file's own format that changes what "+
					"encloses the text that follows. Escape it, or if the role change is genuinely "+
					"intended, make the edit with dry_run first and inspect the diff by hand.",
				off, roleOrig, roleNew)
		}
	}
	return nil
}

// ── markers ──────────────────────────────────────────────────────────

func genMarker(existingText string) string {
	for {
		var seed [16]byte
		_, _ = rand.Read(seed[:])
		h := sha256.Sum256(seed[:])
		b32 := strings.ToLower(strings.TrimRight(base32.StdEncoding.EncodeToString(h[:]), "="))
		marker := MarkerOpen + "RM:" + b32[:16] + MarkerClose
		if !strings.Contains(existingText, marker) {
			return marker
		}
	}
}

// ── small local helpers ──────────────────────────────────────────────

func extOrNoExt(ext string) string {
	if ext == "" {
		return "(no extension)"
	}
	return ext
}
